name: Deploy to GitHub Pages

on:
  push:
    paths:
      - docs/*.json
      - docs/*.html
      - docs/assets/**  # List directories here

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # Auth token for GitHub Pages
        publish_dir: ./docs  # Directory containing the static site files
