name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Run the workflow whenever there's a push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Node.js (optional, only if you use npm or JavaScript tools)
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    # Step 3: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # Auth token for GitHub Pages
        publish_dir: ./docs  # Directory containing the static site files
